import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated sidebar configuration.
 *
 * This uses Docusaurus's autogenerated sidebar feature which automatically
 * creates sidebar items based on the docs folder structure.
 *
 * Category labels and positions are controlled by _category_.json files
 * in each folder. Document order is controlled by sidebar_position in
 * frontmatter.
 *
 * @see https://docusaurus.io/docs/sidebar#sidebar-item-autogenerated
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from the docs folder
    },
  ],
};

export default sidebars;
